config/routes.rb
Rails.application.routes.draw do
		resources :posts
		resources :users
		resources :sessions, only: [:new, :create, :destroy]
		# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
		
		
		get 'sessions/new'
		get 'sessions/create'
		get 'sessions/destroy'
		
		#get 'signup', to: 'users#new', as: 'signup'
		get 'login', to: 'sessions#new', as: 'login'
		get 'admin', to: 'sessions#new', as: 'admin'
		get 'logout', to: 'sessions#destroy', as: 'logoutings'
		get '/error', to: 'users#error', as: 'error'
		get '/rate/:postid/:rating', to: 'posts#rate', as: 'rating'
		get '/image/:id/:email/', constraints: { email: /[^\/]+/}, to: 'posts#user_show'
		get '/passwordchange/', to: 'users#change_password'
	        get '/passwordchagne/', to: 'users#change_password'
		get '/en/', to: 'posts#user_start_page_en'
		post '/passwordchanging/', to: 'users#change_password_post'
		
		root 'posts#user_start_page'

		#get '*path', to: 'users#error'
  		get '*path', to: 'users#error', constraints: lambda { |req|
	    		req.path.exclude? 'rails/active_storage'
  		}
		
		#root 'posts#start_page'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, dependent: :destroy

  validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    if current_user
        @users = User.all
    else
        redirect_to "/error"
    end
  end

  # GET /users/1
  def show
      redirect_to error_path, notice: 'Ólöglegt.'
  end

  def change_password
	if current_user
		render :new_password
	else
		redirect_to error_path, notice: 'Ólöglegt!'
	end
  end

  def change_password_post
	if params[:password]
		x = User.find(current_user.id)
		x.password_digest = BCrypt::Password.create(params[:password])
		if x.save
			redirect_to error_path, notice: "Lykilorði breytt"
		else
			redirect_to error_path, notice: "Eitthvað fór úrskeiðis. Hafðu samband við vefstjóra"
		end
	else
		redirect_to error_path, notice: "Lykilorð má ekki vera tómt"
	end
  end
		

  # GET /users/new
  def new
      redirect_to error_path, notice: 'Ólöglegt.'
  end

  # GET /users/1/edit
  def edit
      redirect_to error_path, notice: 'Ólöglegt.'
  end

  # POST /users
  def create
    redirect_to error_path, notice: 'Ólöglegt.'
    #@user = User.new(user_params)

    #@user.judge = false
    #@user.admin = false

    #if @user.save
    #  redirect_to root_path, notice: 'User was successfully created.'
    #else
    #  render :new
    #end
  end

  # PATCH/PUT /users/1
  def update
    if true
      redirect_to error_path, notice: 'Ólöglegt.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    #@user.destroy
    redirect_to error_path, notice: 'Ólöglegt.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_footer.html.erb
<h3><%= link_to "Útskrá", logoutings_path %></h3>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label "Lykilorð" %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label "Staðfesta lykilorð" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit "Stofna aðgang" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/error.html.erb
<% unless notice.nil? %>
  <h1><%= notice %></h1>
<% else %>
  <h1>Eitthvað fór úrskeiðis</h1>
<% end %>

<%= link_to "Heim", root_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Nýr notandi</h1>

<%= render 'form', user: @user %>

<%= link_to 'Til baka', root_path %>

app/views/users/new_password.html.erb
<%= form_tag("/passwordchanging") do %>
  <div class="field">
    <p>Nýtt lykilorð</p>
	<%= password_field_tag(:password) %>
  </div>

  <div class="actions">
	<%= submit_tag("Breyta lykilorði") %>
  </div>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Back', root_path %>

<%= render 'footer' %>