config/routes.rb
Rails.application.routes.draw do
		resources :posts
		resources :users
		resources :sessions, only: [:new, :create, :destroy]
		# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
		
		
		get 'sessions/new'
		get 'sessions/create'
		get 'sessions/destroy'
		
		#get 'signup', to: 'users#new', as: 'signup'
		get 'login', to: 'sessions#new', as: 'login'
		get 'admin', to: 'sessions#new', as: 'admin'
		get 'logout', to: 'sessions#destroy', as: 'logoutings'
		get '/error', to: 'users#error', as: 'error'
		get '/rate/:postid/:rating', to: 'posts#rate', as: 'rating'
		get '/image/:id/:email/', constraints: { email: /[^\/]+/}, to: 'posts#user_show'
		get '/passwordchange/', to: 'users#change_password'
	        get '/passwordchagne/', to: 'users#change_password'
		get '/en/', to: 'posts#user_start_page_en'
		post '/passwordchanging/', to: 'users#change_password_post'
		
		root 'posts#user_start_page'

		#get '*path', to: 'users#error'
  		get '*path', to: 'users#error', constraints: lambda { |req|
	    		req.path.exclude? 'rails/active_storage'
  		}
		
		#root 'posts#start_page'
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image

    validates :title, presence: true, length: {minimum: 1, maximum: 20}
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
    validate :image_type
    validate :content_length

    def thumbnail
        return self.image.variant(resize: '200x200');
    end

    private

    def image_type
	    if image.attached?
           	if !image.content_type.in?(%('image/jpeg image/png'))
           	    errors.add(:image, 'Mynd verður að vera JPEG/JPG eða PNG')
           	end
	    else
	    	errors.add(:image, "Vantar mynd!")
	    end
    end

    def content_length
        if content.length > 240
            errors.add(:content, "Texti við mynd: Vinsamlegast 240 stafir eða minna")
        end
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    # GET /posts
    def index
        if current_user && (current_user.judge || current_user.admin) then
            @posts = Post.all
        else
            redirect_to error_path, notice: 'Þarft að vera dómari til að sjá alla pósta'
        end
    end

    # GET /posts/1
    def show
        unless current_user
            redirect_to error_path, notice: "Aðeins dómarar hafa aðgang að þessu vefsvæði"
        else
            @user = current_user
        end
    end

    def user_show
        @post = Post.find(params[:id])
        if @post.email != params[:email]
            redirect_to error_path, notice: "Þú hefur ekki réttindin til að skoða þessa mynd. Email vantar til sönnunar"
        end
    end

    def rate
        unless current_user && current_user.judge
            redirect_to error_path, notice: 'Getur ekki gefið mynd einkunn nema þú sért dómari'
        else
            unless Post.exists?(id: params[:postid])
                redirect_to error_path, notice: "Mynd með id:#{params[:postid]} fannst ekki"
            else
                unless params[:rating].to_i <= 10 && params[:rating].to_i >= 1
                    redirect_to error_path, notice: "Einkunnargjöf á að vera á bilinu 1-10"
                else
                    if Rating.exists?(user_id: current_user.id, post_id: params[:postid])
                        rating = Rating.find_by(user_id: current_user.id, post_id: params[:postid])
                        rating.value = params[:rating]
                        if rating.save
                            redirect_to root_path, notice: "Uppfærsla á einkunnargjöf tókst"
                        else
                            redirect_to error_path, notice: "Einkunnargjöf mistókst. Ertu að gefa slóða handvirkt?"
                        end
                    else
                        rating = Rating.new(user_id: current_user.id, post_id: params[:postid], value: params[:rating])
                        if rating.save
                            redirect_to root_path, notice: "Einkunnargjöf tókst"
                        else
                            redirect_to error_path, notice: "Einkunnargjöf mistókst. Ertu að gefa slóða handvirkt?"
                        end
                    end
                end
            end
        end
    end

    # GET /posts/new
    def new
	unless Date.today >= Date.new(2019, 5, 21)
	        @post = Post.new
	else
		render :done
	end
    end

    def user_start_page
        unless current_user.nil?
            @user = current_user

            if current_user.admin
                @ratings = Rating.all
                @posts = Post.where(deleted: false)
		if @posts.count == 0
			@posts = []
			@ratings = []
		end

                @post_ratings = Hash.new{0}
                @post_vote_count = Hash.new{0}
                @post_weighted_ratings = Hash.new{0}

		@posts.each do |post|
		    @post_ratings[post.id] = 0
                    @post_weighted_ratings[post.id] = 0
                    @post_vote_count[post.id] = 0
 
		end

                @ratings.each do |rating|
		    unless Post.find(rating.post_id).deleted
                    	@post_ratings[rating.post_id] += rating.value 
                    	@post_weighted_ratings[rating.post_id] += rating.value
                    	@post_vote_count[rating.post_id] += 1
		    end
                end

                @judge_count = 0

                User.all.each do |user|
                    if user.judge
                        @judge_count += 1
                    end
                end

                @post_weighted_ratings.each do |k, v|
                    @post_weighted_ratings[k] = v.to_f / @judge_count
                end

                @posts_sorted_by_weighted_value = @post_weighted_ratings.sort_by { |k, v| v}.reverse
                render :admin_page
            else
                render :judge_page
            end
        else
		unless Date.today >= Date.new(2019, 5, 21)
		    @post = Post.new
       		    render :new
		else
		    render :done
		end
		
        end
    end

    def user_start_page_en
        unless current_user.nil?
            @user = current_user

            if current_user.admin
                @ratings = Rating.all
                @posts = Post.where(deleted: false)
		if @posts.count == 0
			@posts = []
			@ratings = []
		end

                @post_ratings = Hash.new{0}
                @post_vote_count = Hash.new{0}
                @post_weighted_ratings = Hash.new{0}

		@posts.each do |post|
		    @post_ratings[post.id] = 0
                    @post_weighted_ratings[post.id] = 0
                    @post_vote_count[post.id] = 0
 
		end

                @ratings.each do |rating|
		    unless Post.find(rating.post_id).deleted
                    	@post_ratings[rating.post_id] += rating.value 
                    	@post_weighted_ratings[rating.post_id] += rating.value
                    	@post_vote_count[rating.post_id] += 1
		    end
                end

                @judge_count = 0

                User.all.each do |user|
                    if user.judge
                        @judge_count += 1
                    end
                end

                @post_weighted_ratings.each do |k, v|
                    @post_weighted_ratings[k] = v.to_f / @judge_count
                end

                @posts_sorted_by_weighted_value = @post_weighted_ratings.sort_by { |k, v| v}.reverse
                render :admin_page
            else
                render :judge_page
            end
        else
	    unless Date.today >= Date.new(2019, 5, 21)
		    @post = Post.new
	            render :new_en
	    else
		render :done
	    end
        end
    end


    # GET /posts/1/edit
    def edit
        if current_user
            @post = Post.new
        else
            render :not_logged_in
        end
    end

    # POST /posts
    def create
        #unless current_user
        #    redirect_to error_path, notice: 'Þarft að vera innskráður notandi til að senda inn mynd'
        #end


        @post = Post.new(post_params)
        @post.deleted = false

        if @post.save
            if Post.where(email: @post.email, deleted: false).count > 3
              y = Post.where(email: @post.email, deleted: false).order(created_at: :asc)[0]
              y.deleted = true
              y.save
              redirect_to "/image/#{@post.id}/#{@post.email}", notice: "VINSAMLEGAST ATHUGIÐ. Þrjár myndir frá þér voru þegar í kerfinu. Elstu myndinni þinni með titilinn '#{y.title}' var eytt úr kerfinu."
            else
              redirect_to "/image/#{@post.id}/#{@post.email}", notice: 'Mynd móttekin.'
            end
        else
            render :new
        end
    end

    # PATCH/PUT /posts/1
    def update
        redirect_to error_path, notice: "Ólögleg aðgerð"
        #if @post.update(post_params)
        #    redirect_to @post, notice: 'Post was successfully updated.'
        #else
        #    render :edit
        #end
    end

    # DELETE /posts/1
    def destroy
        unless current_user && (current_user.judge || current_user.admin)
            redirect_to error_path, notice: "Ólögleg aðgerð. Þarft að vera stjórnandi eða eigandi myndar til að eyða henni"
	else
	        #@post.destroy
		@post.deleted = true
		if @post.save then
	       		redirect_to root_path, notice: 'Mynd var eytt'
		else
			redirect_to error_path, notice: 'Ekki tókst að eyða mynd, vinsamlegast hafðu samband við vefstjórnanda'
		end
        end
   end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
        @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
        params.require(:post).permit(:title, :content, :image, :email)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_footer.html.erb
<h3><%= link_to "Útskrá", logoutings_path %></h3>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <!--<h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>-->
      <h2>Eitthvað kom í veg fyrir að myndin var vistuð</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label "Tölvupóstur" %>
    <%= form.text_field :email, class: "form-control", maxlength: "255", 
      required: "required",
      oninvalid: 'setCustomValidity("Þurfum tölvupóst, max 255 stafir")',
      oninput: 'setCustomValidity("")'
    %>
  </div>

  <div class="field form-group">
    <%= form.label "Titill" %>
    <%= form.text_field :title, class: "form-control", maxlength: "20", required: "required",
      oninvalid: 'setCustomValidity("Mynd þarf titil, mest 20 stafir")',
      oninput: 'setCustomValidity("")'
    %>
  </div>

  <div class="field form-group">
    <%= form.label "Texti við mynd" %>
    <%= form.text_area :content, class: "form-control", maxlength: "240" %>
  </div>

  <div class="field form-group">
    <%= form.label "Hlaða upp mynd" %>
    <%= form.file_field :image, :onchange => 'previewImage(this)', direct_upload: true, :class => "form-control-file", accept: "images/*" %>
  </div>

  <div class="actions">
    <%= form.submit "Senda inn mynd", class: "btn btn-primary", id: "submitter" %>
  </div>
<% end %>

app/views/posts/_form_en.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <!--<h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>-->
      <h2>Something prevented your photo from being saved</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label "Email" %>
    <%= form.text_field :email, class: "form-control", maxlength: "255", 
      required: "required",
      oninvalid: 'setCustomValidity("Email is required, at most 255 characters of length")',
      oninput: 'setCustomValidity("")'
    %>
  </div>

  <div class="field form-group">
    <%= form.label "Title" %>
    <%= form.text_field :title, class: "form-control", maxlength: "20", required: "required",
      oninvalid: 'setCustomValidity("Title cannot be longer than 20 characters")',
      oninput: 'setCustomValidity("")'
    %>
  </div>

  <div class="field form-group">
    <%= form.label "Photo description" %>
    <%= form.text_area :content, class: "form-control", maxlength: "240" %>
  </div>

  <div class="field form-group">
    <%= form.label "Upload picture" %>
    <%= form.file_field :image, :onchange => 'previewImage(this)', direct_upload: true, :class => "form-control-file", accept: "images/*" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit picture", class: "btn btn-primary", id: "submitter" %>
  </div>
<% end %>

app/views/posts/admin_page.html.erb
<h1>Sæll ofurstjórnandi</h1>
<%= render 'footer' %>

<p>Það eru <%= @judge_count %> dómarar skráðir inni í kerfið </p>
<p>Vegin einkunn er heildareinkunn deilt með fjölda dómara</p>
<p>Kemur í veg fyrir að ef einn dómari gefur full stig en enginn annar kýs þá fer hún ekki sjálfkrafa á toppinn</p>
<hr />

<table>
  <thead>
    <tr>
      <th>Myndatitill</th>
      <th>Vegin einkunn</th>
      <th>Heildareinkunn</th>
      <th>Fjöldi atkvæða</th>
      <th colspan=2></th>
    </tr>
  </thead>

  <tbody>
    <% @posts_sorted_by_weighted_value.each do |post| %>
	<% puts "sorted #{@posts_sorted_by_weighted_value.count}" %>
	<% puts "SHOULD NOT BE HERE" %>
      <tr>
        <% post = @posts.find(post[0]) %>
        <td><%= post.title %></td>
        <td><%= @post_weighted_ratings[post.id].round(2) %></td>
        <td><%= @post_ratings[post.id] %></td>
        <td><%= @post_vote_count[post.id] %></td>
        <td><%= link_to "Skoða", post_path(post.id) %></td>
        <td><%= image_tag(post.thumbnail) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/done.html.erb
<div class="new-parent">
    <div class="parent-inner">
        <h4>Skilafrestur var til 20.maí, 23:59</h4>
        <p>Þökkum þáttökuna</p>
        <br>
        <hr>
        <br>
        <h4>The deadline for submissions was for May 20th, 23:59</h4>
        <p>Thanks for participating</p>
    </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/judge_page.html.erb
<p id="notice"><%= notice %></p>
<h1>Sæll, dómari</h1>
<p><%= link_to "Skrá út", logoutings_path %></p>

<% @ratings = Rating.where(user_id: @user.id) %>
<% if @ratings.nil? %>
  <% @ratings = [] %>
<% end %>
<% @rated_posts_ids = [] %>
<% @ratings.each do |rating| %>
  <% @rated_posts_ids.push(rating.post_id) %>
<% end %>

<% @posts = Post.where(deleted: false) %>
<% if @posts.nil? || @posts.count == 0 %>
  <% @posts = [] %>
  <% @ratings = [] %>
<% end %>

<% @rated_posts   = @posts.select { |post| @rated_posts_ids.include?(post.id) }%>
<% @unrated_posts = @posts.select { |post| !@rated_posts_ids.include?(post.id) }%>

<table>
  <thead>
    <tr>
      <th>Myndir sem þú átt eftir að gefa einkunn</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% if @unrated_posts.count == 0 %>
      <tr>
        <td>Engar myndir í kerfinu</td>
        <td>Jöss, þú þarft ekkert að gera</td>
      </tr>
    <% end %>
    <% @unrated_posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= link_to "Skoða", post_path(post.id) %></td>
        <td><%= image_tag(post.thumbnail) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr style="border:none; height: 40px; background-color: #000; margin-top: 30px; margin-bottom: 30px" />

<% if @rated_posts.count > 0 %>
  <table>
    <thead>
      <tr>
        <th>Myndir sem þú hefur gefið einkunn</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @rated_posts.each do |post| %>
        <tr>
          <td><%= post.title %> <br><br><i>Þín einkunn: <%= Rating.find_by(user_id: @user.id, post_id: post.id).value %></i></td>
          <td><%= link_to "Skoða", post_path(post.id) %></td>
          <td><%= image_tag(post.thumbnail) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/posts/new.html.erb
<div class="new-parent">
    <div class="parent-inner">
        <div class="myndform">
        <h1>Senda inn mynd</h1>
	<%= link_to "Click here for English", en_path %>
        <p>Sýnishorn mun birtast af myndinni þinni fyrir neðan <u>EKKI í fullri stærð</u></p>
        <p>Þegar myndinni hefur verið hlaðið upp verður þér beint á síðu sem sýnir þér inleggið þitt</p>
        <p>Ef þú vilt geta skoðað innlegg þitt aftur skaltu afrita slóðann þinn úr vafranum en hann verður á forminu https://astrokeppni.com/image/1234/þitt@email.is</p>
	<p>Ef villa kemur upp eða samband þarf að hafa við vefumsjónarmann þá er hægt að senda línu á <a href="mailto:steinerinn@gmail.com">steinerinn@gmail.com</a></p>
        <%= render 'form', post: @post %>
        <img id="prev-img" src="#" alt="" />
        </div>
    </div>
</div>

app/views/posts/new_en.html.erb
<div class="new-parent">
    <div class="parent-inner">
        <div class="myndform">
        <h1>Submit photo</h1>
	<p>A sample photo will appear down below for confirmation <u>but not full size</u></p>
	<p>When your photo has been uploaded you will be redirected to a page which shows your submission</p>
	<p>If you want to look at your submission again at a later time then copy the URL from your browser which will be on the form https://astrokeppni.com/image/1234/your@email.com</p>
	<p>If an error occurs or if you need to contact the webmaster for another reason, you can send an email to <a href="mailto:steinerinn@gmail.com">steinerinn@gmail.com</a></p>
        <%= render 'form_en', post: @post %>
        <img id="prev-img" src="#" alt="" />
        </div>
    </div>
</div>

app/views/posts/not_logged_in.html.erb
<h1>Til að geta sent inn mynd þarftu notandaaðgang</h1>

<p><%= link_to "Innskrá", login_path %></p>
<p><%= link_to "Stofna aðgang", signup_path %></p>

app/views/posts/show.html.erb
<div>
<%= link_to 'Til baka', root_path %>
<% if @user.judge || @user.admin %>
    <%= link_to 'EYÐA MYND!', @post, method: :delete, data: { confirm: 'Ertu viss um að þú viljir eyða mynd?' } %>
<% end %>

<p id="notice"><%= notice %></p>
<% if @user.nil? %>
    <% @userstruct = Struct.new(:judge) %>
    <% @user = @userstruct.new %>
    <% @user.judge = false %>
<% end %>

<% if @user.admin %>
    <% if Rating.find_by(post_id: @post.id) %>
	<% @ratings = Rating.where(post_id: @post.id) %>
    <% else %>
	<% @ratings = [] %>
    <% end %>

   <% @judges = User.all.select{|u| u.judge } %>
   <% @raters = @ratings.collect{|r| r.user_id} %>

   <h2>Dómarar sem hafa gefið myndinni einkunn</h2>
	<ul>
	    <% @judges.each do |judge| %>
		<% if @raters.include?(judge.id) %>
		    <li><%=judge.email%>, einkunn: <%= Rating.find_by(post_id: @post.id, user_id: judge.id).value %></li>
		<% end %>
	    <% end %>
	</ul>

   <h2>Dómarar sem eiga eftir að gefa einkunn</h2>
	<ul>
	    <% @judges.each do |judge| %>
		<% unless @raters.include?(judge.id) %>
		    <li><%=judge.email%></li>
		<% end %>
	    <% end %>
	</ul>


<% end %>

<% if @user.judge %>
    <% @picture_owner = @post.email %>
    <% if Rating.find_by(user_id: @user.id, post_id: @post.id) %>
        <% @rating = Rating.find_by(user_id: @user.id, post_id: @post.id) %>
        <p><strong>Þú hefur gefið einkunn:</strong><%= @rating.value %></p>
        <h1>Uppfæra einkunn</h1>
    <% else %>
        <h1>Gefa einkunn</h1>
    <% end %>

    <% 10.times.with_index do |i| %>
        <h2 style="display: inline-block"><%= link_to (i+1), "/rate/#{@post.id}/#{i+1}" %></h2>
    <% end %>

<% end %>

<% #delete true to re-enable innsendandi %>
<% unless @picture_owner.nil? || true %>
    <p>
    <strong>Innsendandi:</strong>
    <%= @picture_owner %>
    </p>
<% end %>

<p>
<strong>Titill:</strong>
<%= @post.title %>
</p>

<p>
<strong>Um mynd:</strong>
<%= @post.content %>
</p>

<% if @post.image.attached? %>
    <!-- @post.image.present? will always return true, use attached? to check presence -->
    <p>
    <strong>Mynd (smelltu á mynd til að stækka):</strong>
    <br>
    <%= image_tag @post.image, :class => "fullstort" %>
    </p>
<% end %>
</div>

<script>registerImages()</script>

app/views/posts/user_show.html.erb
<div>
<%= link_to 'Til baka', root_path %>
<p id="notice"><%= notice %></p>

<p>
<strong>Titill:</strong>
<%= @post.title %>
</p>

<p>
<strong>Um mynd:</strong>
<%= @post.content %>
</p>

<% if @post.image.attached? %>
    <!-- @post.image.present? will always return true, use attached? to check presence -->
    <p>
    <strong>Mynd (smelltu á mynd til að stækka):</strong>
    <br>
    <%= image_tag @post.image, :class => "fullstort" %>
    </p>
<% end %>


</div>
<script>registerImages()</script>

app/views/posts/user_start_page.html.erb
<p id="notice"><%= notice %></p>

<% unless @user.judge %>
  <h1>Ljósmyndakeppni</h1>

  <table>
    <thead>
      <tr>
        <th>Myndir</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% if @posts.count == 0 %>
        <tr>
          <td>Þú hefur ekki hlaðið upp neinum myndum </td>
          <td>Smelltu á 'Ný mynd' hér fyrir neðan</td>
        </tr>
      <% end %>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= link_to "Skoða", post_path(post.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Ný mynd', new_post_path %>

<% else %>
  <h1>Sæll, dómari</h1>

  <% @ratings = Rating.where(user_id: @user.id) %>
  <% if @ratings.nil? %>
    <% @ratings = [] %>
  <% end %>
  <% @rated_posts_ids = [] %>
  <% @ratings.each do |rating| %>
    <% @rated_posts_ids.push(rating.post_id) %>
  <% end %>

  <% @posts = Post.all %>
  <% if @posts.nil? || @posts.count == 0 %>
    <% @posts = [] %>
  <% end %>

  <% @rated_posts   = @posts.select { |post| @rated_posts_ids.include?(post.id) }%>
  <% @unrated_posts = @posts.select { |post| !@rated_posts_ids.include?(post.id) }%>



  <table>
    <thead>
      <tr>
        <th>Myndir sem þú átt eftir að gefa einkunn</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% if @unrated_posts.count == 0 %>
        <tr>
          <td>Engar myndir í kerfinu</td>
          <td>Jöss, þú þarft ekkert að gera</td>
        </tr>
      <% end %>
      <% @unrated_posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= link_to "Skoða", post_path(post.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if @rated_posts.count > 0 %>
    <table>
      <thead>
        <tr>
          <th>Myndir sem þú hefur gefið einkunn</th>
          <th colspan="1"></th>
        </tr>
      </thead>

      <tbody>
        <% @rated_posts.each do |post| %>
          <tr>
            <td><%= post.title %></td>
            <td><%= link_to "Skoða", post_path(post.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>